name: Image Builder

on:
  push:
    branches:
      - master
      - main
  
jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Checkout repo to get tools version
        uses: actions/checkout@master
        with: 
          repository: phosae/echo-server
          path: ./echo-server

      - name: Short Commit ID
        id: commit
        run: |
          echo "COMMIT_ID=$(git --git-dir=./echo-server/.git --work-tree=./echo-server rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: zengxu
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build image and push to Docker Hub 
        uses: docker/build-push-action@v3
        with:
          context: ./echo-server
          tags: |
            zengxu/echo-server:${{ env.COMMIT_ID }},zengxu/echo-server:latest
          platforms: |
            linux/amd64,linux/arm64
          push: ${{ github.ref == 'refs/heads/master' }}